name = "Herring Cove Solarized"
description = ""
license = "MIT"
tags = ["blog", "company"]
min_version = 0.20

[author]
    name = "cognitiaclaeves"
    homepage = "http://zen-techie.com/"

# If Porting existing theme
#[original]
#    author =  "arnp"
#    repo = "http://www.github.com/arnp/herring-cove"
